### PR TITLE
Add travis and docker compose for depedencies

### PR DESCRIPTION
**Pull request by chbatey**
Will also add an integration test

### CODE REVIEW

**Review by octonato — DISMISSED** [review]
LGTM

But tests are failing because of Lightbend credentials.

**Comment by chbatey** [comment]
Got quite a bit more to add to this.

**Comment by octonato** [comment]
Yep, since you are adding changing the travis.yml, we can also remove the branch building.

**Comment by octonato** [comment]
@chbatey, why do we need Cinnamon on this project? Could we remove it to make it simpler and easier to manage?

**Comment by chbatey** [comment]
I can comment out cinnamon but it makes doing any analysis much easier

**Comment by chbatey** [comment]
I've added an integration test and now it is run in travis. Ready for review

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
